
import { Language, DoctorProfile, PatientSummary, User, Role } from './types';

export const usersData: User[] = [
  {
    id: 'ADM-1',
    name: 'System Admin',
    mobile: '00000',
    idCardNo: '00000-0000000-0',
    role: Role.ADMIN,
    language: 'en',
    password: 'admin'
  }
];

export const CONFIDENCE_LEVELS = {
  HIGH: { en: 'Clinical Confidence: High', ur: 'طبی اعتماد: مکمل (قابلِ بھروسہ)', color: 'text-emerald-500', icon: '✅' },
  MEDIUM: { en: 'Clinical Confidence: Moderate', ur: 'طبی اعتماد: اوسط (جائزہ ضروری)', color: 'text-amber-500', icon: '⚠️' },
  LOW: { en: 'Clinical Confidence: Advisory Only', ur: 'طبی اعتماد: محض مشورہ (ڈاکٹر سے رجوع کریں)', color: 'text-rose-500', icon: '❌' }
};

export const doctorsData: DoctorProfile[] = [
  {
    id: 'DOC-1',
    name: { en: 'Dr. Sarah Ahmed', ur: 'ڈاکٹر سارہ احمد' },
    specialization: { en: 'General Physician', ur: 'جنرل فزیشن' },
    phone: '+92-300-1234567',
    availability: [
      { date: '2026-01-02', times: ['09:00', '10:00', '11:00', '14:00', '15:00'] },
      { date: '2026-01-03', times: ['09:00', '10:00', '11:00', '14:00', '15:00'] },
      { date: '2026-01-04', times: ['09:00', '10:00', '11:00'] }
    ]
  },
  {
    id: 'DOC-2',
    name: { en: 'Dr. Ali Khan', ur: 'ڈاکٹر علی خان' },
    specialization: { en: 'Cardiologist', ur: 'ماہر امراض قلب' },
    phone: '+92-301-2345678',
    availability: [
      { date: '2026-01-02', times: ['10:00', '11:00', '15:00', '16:00'] },
      { date: '2026-01-03', times: ['10:00', '11:00', '15:00', '16:00'] },
      { date: '2026-01-05', times: ['09:00', '10:00', '11:00'] }
    ]
  },
  {
    id: 'DOC-3',
    name: { en: 'Dr. Fatima Malik', ur: 'ڈاکٹر فاطمہ ملک' },
    specialization: { en: 'Pediatrician', ur: 'ماہر اطفال' },
    phone: '+92-302-3456789',
    availability: [
      { date: '2026-01-02', times: ['08:00', '09:00', '10:00', '14:00'] },
      { date: '2026-01-03', times: ['08:00', '09:00', '10:00', '14:00'] },
      { date: '2026-01-04', times: ['08:00', '09:00', '10:00'] }
    ]
  }
];

export const patientSummariesData: PatientSummary[] = [];

const enStrings = {
  welcomeTitle: 'Welcome to Alshifa AI',
  patientPortalTitle: 'Patient Portal',
  patientPortalDesc: 'Register or Login as a Patient',
  doctorPortalTitle: 'Doctor Portal',
  doctorPortalDesc: 'Register or Login as a Doctor',
  securityNote: 'Security Note: System Admin role removed per security policy.',
  systemAccessDenied: 'Access Denied. Please login.',
  accessDeniedDoctor: 'Access Denied. Please login as a Doctor.',
  accessDeniedPatient: 'Access Denied. Please login as a Patient.',
  backToLogin: 'Back to Login',
  profileNotFound: 'Profile Not Found',
  resyncingProfile: 'Resyncing Doctor Profile...',

  patient: 'Patient',
  doctor: 'Physician',
  admin: 'System Admin',
  login: 'Login',
  register: 'Register',
  back: 'Back',
  logout: 'Logout',
  welcomeMessage: 'Hello! I am Alshifa AI Medical Assistant. Please describe your symptoms in detail so I can assist your physician.',
  followUpWelcome: 'Welcome back. I have your previous history on file. How have your symptoms changed since our last visit?',
  botThinking: 'Alshifa AI Medical Assistant is meticulously analyzing your symptoms...',
  viewSummary: 'Review Triage Summary',
  doctorDashboard: 'Physician Dashboard',
  upcomingAppointments: 'Scheduled Patients',
  searchPatientPlaceholder: 'Search patients...',
  summaryForDoctor: 'Medical Intake Summary',
  patientHistory: 'Previous Consultations',
  clinicalOverview: 'Overview',
  overviewTab: 'Overview',
  testsTab: 'Tests',
  medsTab: 'Medication',
  transcriptTab: 'Transcript',
  historyTab: 'History',
  approve: 'Approve',
  reject: 'Reject',
  runAnalysis: 'Run AI Analysis',
  approveAnalysis: 'Approve Interpretation',
  testSuggested: 'AI Suggested',
  testApproved: 'Order Released',
  testUploaded: 'Report Received',
  testAi_analyzed: 'AI Analyzed',
  testDoctor_approved: 'Doctor Validated',
  testPending: 'Pending',
  testRejected: 'Rejected',
  stopMed: 'Stop Medication',
  adherence: 'Adherence',
  adherenceRate: 'Adherence Rate',
  dose: 'Dose',
  frequency: 'Frequency',
  duration: 'Duration',
  endsOn: 'Ends On',
  dosage: 'Dosage',
  history: 'History',
  current: 'Current',
  patientInstructions: 'Instructions for Patient',
  finalizeConsultation: 'Finalize Consultation',
  aiCoach: 'AI Health Coach',
  myMedication: 'My Medication',
  myHealthDashboard: 'Patient Health Portal',
  viewDetails: 'View Details',
  sessionDetails: 'Session Details',
  consultationSessions: 'Consultation Sessions',
  sessionChoice: 'Patient Portal',
  startNewSession: 'Book Consultation',
  viewHistory: 'Clinical History',
  bookAppointment: 'Book Now',
  selectDoctor: 'Select Physician',
  nextAvailable: 'Next Available',
  appointmentWith: 'Appointment with',
  date: 'Date',
  availableSlots: 'Available Slots',
  howToProceed: 'How would you like to proceed?',
  startIntakeProcess: 'Start AI Intake',
  startOnlineConsultationNow: 'Video Consultation',
  authChoiceTitle: 'Welcome to Alshifa AI Medical Assistant',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  yourMobile: 'Mobile Number',
  dateOfBirth: 'Date of Birth',
  sexAtBirth: 'Sex at Birth',
  idCardNo: 'ID Card Number',
  country: 'Country',
  male: 'Male',
  female: 'Female',
  intersex: 'Intersex',
  preferNotToSay: 'Prefer not to say',
  completeRegistration: 'Complete Your Account',
  yourName: 'Full Name',
  selectDoctorLogin: 'Select your name',
  noAccount: "Don't have an account? Register here",
  alreadyHaveAccount: "Already have an account? Login here",
  addNote: 'Add Private Note',
  saveNote: 'Save Note',
  cancel: 'Cancel',
  finish: 'Complete Triage',
  provideFeedback: 'AI Accuracy Feedback',
  saveFeedback: 'Submit Feedback',
  feedbackSaved: 'Feedback saved successfully.',
  passwordsDoNotMatch: 'Passwords do not match.',
  passwordTooShort: 'Password must be at least 8 characters, including uppercase, lowercase, and numbers.',
  invalidMobile: 'Please enter a valid mobile number.',
  invalidDOB: 'Please enter a valid date of birth.',
  fillAllFields: 'Please fill all required fields.',
  clinicalAnalytics: 'Analytics',
  totalCases: 'Total Cases',
  highRiskCases: 'High Risk',
  doctorOverrides: 'AI Discrepancies',
  adminDashboard: 'Admin Control',
  stockLowWarning: '⚠️ Medication stock is low!',
  medicationLocked: '🔒 Doctor Instruction',
  markAsTaken: 'Taken',
  markAsMissed: 'Missed',
  markNextDoseTaken: 'Mark Next Dose Taken',
  remaining: 'Remaining',
  remainingLabel: 'Left',
  lowStock: 'Low stock',
  criticalStock: 'Out of stock soon!',
  buyReminder: 'Please buy more medicine.',
  pharmacyDirectory: 'Pharmacies',
  callPharmacy: 'Call',
  estimatedPrice: 'Est. Price',
  priceDisclaimer: '*Prices may vary',
  dataSecurityNotice: '🔒 Encrypted Clinical Data',
  intakeModeFirst: 'Initial Clinical Intake',
  intakeModeFollow: 'Follow-up Consultation',
  historySecured: 'Previous medical history is secured.',
  clinicalOrder: 'Doctor Instruction',
  selfMedication: 'Self Medication',
  notDoctorApproved: 'Not Doctor Approved',
  continue: 'Continue',
  submit: 'Submit',
  typeOrSpeak: 'Type your symptoms here...',
  generateSummary: 'Generate Triage Summary',
  uploadResult: 'Upload Result',
  uploadHelp: 'Upload image or file.',
  waitingDoctorReview: 'Waiting for doctor review',
  doctorReviewed: 'Doctor reviewed',
  noMedicationData: 'No medication records found.',
  noTests: 'No tests prescribed for this session.',
  noMeds: 'No medications prescribed in this session.',
  noMedsActive: 'No active medications. Click above to add or scan.',
  noConsultations: 'No clinical records available.',
  genericError: 'Something went wrong. Please try again.',
  appDisclaimer: 'AI does not replace a doctor. Final decisions are always made by your physician.',
  sessionExpired: 'Session expired',
  loginAgain: 'Please login again',
  addMedManually: 'Add Medication Manually',
  scanPrescription: 'Scan Paper Prescription',
  foodRules: {
    before_meal: 'Take 30m before meal',
    after_meal: 'Take after meal',
    with_meal: 'Take with food',
    empty_stomach: 'Take on empty stomach',
    none: 'Take anytime'
  },
  slots: {
    Morning: 'Morning',
    Afternoon: 'Afternoon',
    Evening: 'Evening',
    Night: 'Night'
  },
  adherenceHigh: 'Excellent! You are taking great care of your health.',
  adherenceMid: 'You\'re doing well! A bit more consistency will be even better.',
  adherenceLow: 'If it\'s hard to remember, we can help you set better reminders.',
  calendarMonths: [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ],
  calendarDays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  reminders: {
    onTime: "It's time to take your medicine.",
    late: "You are a bit late taking your medicine. Please take it now if possible.",
    missed: "This dose was missed. If this happens often, please inform your doctor.",
    dailySummary: "One dose was missed yesterday."
  },
  progress: {
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    missedDose: "Missed Dose",
    takenOnTime: "Taken On Time",
    goodJob: "Good job! Keep taking your medication regularly."
  },
  planTab: "Plan",
  pendingTab: "Pending",
  clinicalTab: "Clinical",
  pharmacotherapyPrescriptions: "Pharmacotherapy Prescriptions",
  orderedDiagnosticTests: "Ordered Diagnostic Tests",
  suggestedMedications: "Suggested Medications",
  suggestedTests: "Suggested Tests",
  patientRole: "Patient",
  physicianRole: "Physician",
  adminRole: "System Admin",
  missedDoseLabel: "Missed Dose (Dose رہ جائے)",
  missedDoseDefault: "Take as soon as remembered. Do not double up.",
  warningsLabel: "Warnings (انتباہ)",
  consultDoctorForSideEffects: "Consult doctor for side effects.",
  adherenceHistory: "Adherence History (پابندی)",
  last7Days: "Last 7 Days",
  todaysStatus: "Today's Status",
  taken: "Taken",
  doses: "Doses",
  clinicalAlert: "Clinical Alert",
  missedDoseWarningText: "You have missed recent doses. Please consult your doctor if you are experiencing symptoms.",
  markTodaysDose: "Mark Today's Dose",
  appTitle: "Alshifa AI Medical Assistant",
  appSubtitle: "Clinical Decision Support System",
  search: "Search",
  close: "Close",
  reviewed: "Reviewed",
  pending: "Pending",
  loginAsDoctor: "Login as Doctor",
  loginAsPatient: "Login as Patient",
  planPendingMessage: "Your clinical management plan is being finalized. Instructions will appear here shortly.",
  intake: {
    intro: `Hello 👋
I am Alshifa AI Medical Assistant’s clinical assistant.

I will ask you a few medical questions to better understand your condition.
You can answer in English.

This information is used only to help with your treatment.`,
    chief_complaint: "Please tell me, exactly where and what kind of pain/discomfort are you feeling right now?\n(Example: Leg pain, chest pain, headache, etc.)",
    onset: "When did this pain/discomfort start?\n(Example: Today, yesterday, a few days ago)",
    location: "Is the pain in one specific spot or does it spread elsewhere?\n(Example: Only leg, up to the knee, or to the back)",
    severity: "If 0 means no pain and 10 means very severe pain,\nwhat number would you give your pain?",
    associated_symptoms: "Along with this pain, do you have weakness, numbness, dizziness, or fever?",
    medical_history: "Do you have any pre-existing conditions?\n(Like diabetes, blood pressure, heart disease, etc.)",
    history_clarification: "If you have provided information in this app before, the doctor can see it, but please briefly mention it again for better treatment.",
    medications: "Are you currently taking any regular medications?\nIf yes, please tell me the names.",
    allergies: "Do you have any drug allergies?",
    summary: "Thank you.\nI am now preparing a clinical summary which will be provided to your physician for review.\nThe doctor will evaluate this information and guide your next steps.",
    heartDisease: "Heart Disease",
    diabetes: "Diabetes",
    cancer: "Cancer",
    substance: "Substance",
    reaction: "Reaction",
    add: "Add",
    remove: "Remove",
    name: "Name",
    dose: "Dose"
  }
};

const urStrings = {
  welcomeTitle: 'الشفاء اے آئی میں خوش آمدید',
  patientPortalTitle: 'مریض کا پورٹل',
  patientPortalDesc: 'بطور مریض رجسٹر یا لاگ ان کریں',
  doctorPortalTitle: 'ڈاکٹر کا پورٹل',
  doctorPortalDesc: 'بطور ڈاکٹر رجسٹر یا لاگ ان کریں',
  securityNote: 'سیکیورٹی نوٹ: سسٹم ایڈمن کا کردار سیکیورٹی پالیسی کے تحت ہٹا دیا گیا ہے۔',
  systemAccessDenied: 'رسائی مسترد۔ براہ کرم لاگ ان کریں۔',
  accessDeniedDoctor: 'رسائی مسترد۔ براہ کرم بطور ڈاکٹر لاگ ان کریں۔',
  accessDeniedPatient: 'رسائی مسترد۔ براہ کرم بطور مریض لاگ ان کریں۔',
  backToLogin: 'لاگ ان پر واپس جائیں',
  profileNotFound: 'پروفائل نہیں ملا',
  resyncingProfile: 'ڈاکٹر پروفائل دوبارہ سنک ہو رہی ہے...',



  intake: {
    intro: `السلام علیکم 👋  
میں الشفاء اے آئی میڈیکل اسسٹنٹ کا کلینیکل اسسٹنٹ ہوں۔ ہم آپ کے مسئلے کو سنجیدگی سے سننا چاہتے ہیں تاکہ ڈاکٹر کو آپ کی بہتر رہنمائی میں مدد مل سکے۔

دستیاب معلومات کی بنیاد پر ایک ابتدائی خلاصہ تیار کیا گیا ہے، جس کی تصدیق ڈاکٹر کریں گے۔
اگر آپ چاہیں تو اردو یا سادہ رومن اردو میں جواب دے سکتے ہیں۔

یہ معلومات صرف معاونت کے لیے ہیں، حتمی فیصلہ ڈاکٹر کریں گے۔`,
    welcome: "ہم آپ کی بہتر رہنمائی کے لیے چند سوالات کریں گے۔",
    chief_complaint: `براہِ کرم بتائیں، اس وقت آپ کو سب سے زیادہ کس جگہ اور کس قسم کی تکلیف ہے؟
(مثال: ٹانگ میں درد، سینے میں درد، سر درد وغیرہ)`,
    onset: `یہ تکلیف کب شروع ہوئی؟
(مثال: آج، کل، چند دن پہلے)`,
    location: `کیا درد صرف ایک جگہ ہے یا کہیں اور بھی پھیلتا ہے؟
(مثال: صرف ٹانگ، گھٹنے تک، یا کمر تک)`,
    severity: `اگر 0 کا مطلب بالکل درد نہیں اور 10 کا مطلب بہت شدید درد ہو،
تو آپ اپنے درد کو کتنے نمبر دیں گے؟`,
    associated_symptoms: `کیا اس درد کے ساتھ کمزوری، سن ہونا، چکر، یا بخار بھی ہے؟`,
    medical_history: `کیا آپ کو پہلے سے کوئی بیماری ہے؟
(جیسے شوگر، بلڈ پریشر، دل کی بیماری وغیرہ)`,
    history_clarification: `اگر آپ نے پہلے اس ایپ میں معلومات دی ہوں تو ڈاکٹر کو نظر آ سکتی ہیں،
لیکن ڈاکٹر کے بہتر فیصلے کے لیے براہِ کرم مختصراً بتا دیں۔`,
    medications: `کیا آپ اس وقت کوئی دوا باقاعدگی سے لے رہے ہیں؟
اگر ہاں، تو نام بتا دیں۔`,
    allergies: `کیا آپ کو کسی دوا سے الرجی ہے؟`,
    summary: `آپ کا شکریہ۔  
ت دستیاب معلومات کی بنیاد پر ایک طبی خلاصہ تیار کیا گیا ہے، جس کی تصدیق ڈاکٹر کریں گے۔
ڈاکٹر آپ کی علامات کا جائزہ لے کر حتمی فیصلہ کریں گے اور آگے کی رہنمائی فرمائیں گے۔`,
    heartDisease: "دل کی بیماری (Heart Disease)",
    diabetes: "شوگر (Diabetes)",
    cancer: "کینسر (Cancer)",
    substance: "دوا/چیز (Substance)",
    reaction: "ردعمل (Reaction)",
    add: "شامل کریں",
    remove: "ہٹائیں",
    name: "دوا کا نام",
    dose: "مقدار (Dose)"
  },
  selectYourRole: 'اپنا کردار منتخب کریں',
  patient: 'مریض',
  doctor: 'Physician',
  admin: 'System Admin',
  login: 'لاگ ان',
  register: 'رجسٹریشن',
  back: 'واپس جائیں',
  logout: 'لاگ آؤٹ',
  welcomeMessage: 'ہم آپ کی بہتر رہنمائی کے لیے چند سوالات کریں گے۔',
  followUpWelcome: 'خوش آمدید۔ اگر آپ نے پہلے معلومات دی ہیں تو ڈاکٹر ان کا جائزہ لے سکتے ہیں۔ پچھلی بار کے مقابلے میں آپ کی طبیعت اب کیسی ہے؟',
  botThinking: 'الشفاء اے آئی میڈیکل اسسٹنٹ آپ کی علامات کا تفصیلی جائزہ لے رہا ہے...',
  viewSummary: 'ٹرئیج کا جائزہ لیں',
  doctorDashboard: 'Physician Dashboard',
  upcomingAppointments: 'Scheduled Patients',
  searchPatientPlaceholder: 'Search patients...',
  summaryForDoctor: 'Preliminary Clinical Intake',
  patientHistory: 'طبی تاریخ',
  clinicalOverview: 'خلاصہ',
  overviewTab: "ابتدائی طبی خلاصہ (Preliminary Overview)",
  testsTab: "تجویز کردہ ٹیسٹ (Suggested Tests)",
  medsTab: "تجویز کردہ ادویات (Suggested Medications)",
  historyTab: "طبی ہسٹری (Clinical History)",
  transcriptTab: "انٹیک ٹرانسکرپٹ (Intake Transcript)",
  adherence: 'دوا لینے کی پابندی',
  adherenceRate: 'دوا لینے کی پابندی',
  dose: 'خوراک',
  frequency: 'کتنی بار',
  duration: 'مدت',
  endsOn: 'ختم ہونے کی تاریخ',
  dosage: 'خوراک',
  history: 'طبی تاریخ',
  current: 'موجودہ',
  patientInstructions: 'مریض کے لیے ہدایات',
  finalizeConsultation: 'Finalize Consultation',
  aiCoach: 'AI ہیلتھ کوچ',
  myMedication: 'میری دوائیں',
  myHealthDashboard: 'ڈیش بورڈ',
  viewDetails: 'تفصیل دیکھیں',
  sessionDetails: 'سیشن کی تفصیل',
  consultationSessions: 'مشاورتی سیشن',
  sessionChoice: 'مریض کا پورٹل',
  startNewSession: 'مشاورت بک کریں',
  viewHistory: 'طبی تاریخ',
  bookAppointment: 'بک کریں',
  selectDoctor: 'ڈاکٹر منتخب کریں',
  nextAvailable: 'اگلا دستیاب وقت',
  appointmentWith: 'کے ساتھ اپوائنٹمنٹ',
  date: 'تاریخ',
  availableSlots: 'دستیاب اوقات',
  howToProceed: 'آپ کیسے آگے بڑھنا چاہیں گے؟',
  startIntakeProcess: 'AI انٹیک شروع کریں',
  startOnlineConsultationNow: 'ویڈیو مشاورت',
  authChoiceTitle: 'الشفاء اے آئی میڈیکل اسسٹنٹ میں خوش آمدید',
  password: 'پاس ورڈ',
  confirmPassword: 'پاس ورڈ کی تصدیق',
  yourMobile: 'موبائل نمبر',
  dateOfBirth: 'تاریخِ پیدائش',
  sexAtBirth: 'جنس',
  idCardNo: 'شناختی کارڈ نمبر',
  country: 'ملک',
  male: 'مرد',
  female: 'عورت',
  intersex: 'انٹرسیکس',
  preferNotToSay: 'بتانا پسند نہیں',
  completeRegistration: 'اپنا اکاؤنٹ مکمل کریں',
  yourName: 'مکمل نام',
  selectDoctorLogin: 'Select your name',
  noAccount: 'اکاؤنٹ نہیں ہے؟ یہاں رجسٹریشن کریں',
  alreadyHaveAccount: 'پہلے سے اکاؤنٹ ہے؟ یہاں لاگ ان کریں',
  cancel: 'منسوخ کریں',
  finish: 'ٹرئیج مکمل کریں',
  passwordsDoNotMatch: 'پاس ورڈ میچ نہیں کر رہے۔',
  passwordTooShort: 'پاس ورڈ کم از کم 8 حروف، بڑے اور چھوٹے حروف اور نمبرز پر مشتمل ہونا چاہیے۔',
  invalidMobile: 'براہِ کرم درست موبائل نمبر درج کریں۔',
  invalidDOB: 'براہِ کرم درست تاریخ پیدائش درج کریں۔',
  fillAllFields: 'براہِ کرم تمام ضروری فیلڈز پر کریں۔',
  stockLowWarning: '⚠️ دوا کم ہو رہی ہے!',
  medicationLocked: '🔒 ڈاکٹر کی ہدایت',
  markAsTaken: 'لی گئی',
  markAsMissed: 'چھوٹ گئی',
  markNextDoseTaken: 'اگلی خوراک لیں',
  remainingLabel: 'باقی',
  lowStock: 'دوا کم ہو رہی ہے۔',
  criticalStock: 'دوا ختم ہونے والی ہے۔ اگر ضرورت ہو تو دوبارہ خرید لیں۔',
  buyReminder: 'اگر دوا ختم ہو گئی ہو تو مزید خریدنے کا انتظام کریں۔',
  dataSecurityNotice: '🔒 محفوظ طبی معلومات',
  intakeModeFirst: 'ابتدائی طبی انٹیک',
  intakeModeFollow: 'فالو اپ مشاورت',
  clinicalOrder: 'ڈاکٹر کی ہدایت',
  selfMedication: 'اپنی طرف سے لی گئی دوا',
  notDoctorApproved: 'ڈاکٹر سے منظور شدہ نہیں',
  continue: 'جاری رکھیں',
  submit: 'جمع کروائیں',
  typeOrSpeak: 'اپنی علامات یہاں لکھیں...',
  generateSummary: 'خلاصہ تیار کریں',
  uploadResult: 'ٹیسٹ رپورٹ اپ لوڈ کریں',
  uploadHelp: 'ٹیسٹ کی تصویر یا فائل اپ لوڈ کریں۔',
  waitingDoctorReview: 'ڈاکٹر کے جائزے کا انتظار ہے۔',
  doctorReviewed: 'ڈاکٹر نے رپورٹ دیکھ لی ہے۔',
  noMedicationData: 'اس وقت کوئی دوا موجود نہیں ہے۔',
  noTests: 'ابھی کوئی ٹیسٹ موجود نہیں ہے۔',
  noMeds: 'اس سیشن میں کوئی دوا تجویز نہیں کی گئی۔',
  noMedsActive: 'اس وقت کوئی دوا موجود نہیں ہے۔ نیا نسخہ شامل کرنے کے لیے اوپر دیے گئے بٹن استعمال کریں۔',
  noConsultations: 'کوئی طبی ریکارڈ موجود نہیں ہے۔',
  genericError: 'کچھ مسئلہ پیش آیا ہے۔ براہِ کرم دوبارہ کوشش کریں۔',
  appDisclaimer: 'یہ معلومات صرف معاونت کے لیے ہیں، حتمی تشخیص ڈاکٹر کریں گے۔ الشفاء اے آئی میڈیکل اسسٹنٹ صرف ایک معاون نظام ہے اور یہ کسی بھی صورت میں ڈاکٹر کا متبادل نہیں ہو سکتا۔',
  sessionExpired: 'سیشن ختم ہو گیا ہے۔ دوبارہ لاگ ان کریں۔',
  loginAgain: 'دوبارہ لاگ ان کریں',
  addMedManually: 'دوا شامل کریں (یہ دوا کسی دوسرے ڈاکٹر نے تجویز کی ہو سکتی ہے، صرف ریکارڈ کے لیے)',
  scanPrescription: 'نسخہ اسکین کریں',
  foodRules: {
    before_meal: 'کھانے سے پہلے لیں',
    after_meal: 'کھانے کے بعد لیں',
    with_meal: 'کھانے کے ساتھ لیں',
    empty_stomach: 'نہار منہ لیں',
    none: 'کسی بھی وقت لے سکتے ہیں'
  },
  slots: {
    Morning: 'صبح',
    Afternoon: 'دوپہر',
    Evening: 'شام',
    Night: 'رات'
  },
  adherenceHigh: 'دوا وقت پر لی گئی ہے۔ بہت اچھا 👍',
  adherenceMid: 'آپ اچھا کر رہے ہیں، تھوڑی مزید باقاعدگی آپ کی صحت کے لیے بہتر ہے۔',
  adherenceLow: 'اگر دوا وقت پر لینا مشکل ہو رہا ہو، تو ہم آپ کے لیے یاد دہانی کا وقت تبدیل کر سکتے ہیں۔',
  calendarMonths: [
    'جنوری', 'فروری', 'مارچ', 'اپریل', 'مئی', 'جون',
    'جولائی', 'اگست', 'ستمبر', 'اکتوبر', 'نومبر', 'دسمبر'
  ],
  calendarDays: ['اتوار', 'پیر', 'منگل', 'بدھ', 'جمعرات', 'جمعہ', 'ہفتہ'],
  reminders: {
    onTime: "دوا لینے کا وقت ہو گیا ہے۔",
    late: "دوا لینے میں تھوڑی دیر ہو گئی ہے۔ اگر ممکن ہو تو اب لے لیں۔",
    missed: "یہ خوراک نہیں لی گئی۔ اگر ایسا بار بار ہو رہا ہو تو اپنے ڈاکٹر کو آگاہ کریں۔",
    dailySummary: "کل ایک خوراک نہیں لی جا سکی۔"
  },
  progress: {
    today: "آج",
    yesterday: "کل",
    thisWeek: "اس ہفتے",
    missedDose: "چھوٹی ہوئی خوراک",
    takenOnTime: "وقت پر لی گئی",
    goodJob: "بہت اچھا! دوا باقاعدگی سے لیتے رہیں۔"
  },
  alerts: {
    green: "دوا وقت پر لی گئی ہے۔ بہت اچھا 👍",
    yellow: "دوا لینے کا وقت قریب ختم ہو رہا ہے۔",
    red: "دوا نہیں لی گئی۔ اس سے علاج متاثر ہو سکتا ہے۔"
  },
  planTab: "تجویز کردہ طبی منصوبہ (Proposed Clinical Plan)",
  pendingTab: "زیرِ جائزہ (Under Review)",
  clinicalTab: "کلینیکل ہدایات (Clinical Instructions)",
  pharmacotherapyPrescriptions: "ادویاتی علاج (Pharmacotherapy)",
  orderedDiagnosticTests: "تجویز کردہ تشخیصی ٹیسٹ (Ordered Tests)",
  suggestedMedications: "تجویز کردہ ادویات (Suggested Medications)",
  suggestedTests: "مزید تشخیصی ٹیسٹ (Additional Tests)",
  patientRole: "مریض (Patient)",
  physicianRole: "ڈاکٹر / معالج (Physician)",
  adminRole: "نظام منتظم (System Admin)",
  missedDoseLabel: "اگر خوراک رہ جائے (Missed Dose)",
  missedDoseDefault: "جیسے ہی یاد آئے، خوراک لے لیں۔ اسے دگنا نہ کریں۔",
  warningsLabel: "انتباہ (Warnings)",
  consultDoctorForSideEffects: "سائیڈ ایفیکٹس کے لیے ڈاکٹر سے مشورہ کریں۔",
  adherenceHistory: "دواؤں کی پابندی (Adherence History)",
  last7Days: "گزشتہ 7 روز",
  todaysStatus: "آج کی حالت",
  taken: "لی گئی",
  doses: "خوراکیں",
  clinicalAlert: "کلینیکل الرٹ",
  missedDoseWarningText: "آپ کی حالیہ خوراکیں رہ گئی ہیں۔ اگر آپ کو علامات محسوس ہو رہی ہیں تو براہِ کرم ڈاکٹر سے رجوع کریں۔",
  markTodaysDose: "آج کی خوراک لی گئی",
  appTitle: "الشفاء اے آئی میڈیکل اسسٹنٹ (Alshifa AI)",
  appSubtitle: "طبی معاونت اور فیصلہ سازی کا نظام (Clinical Decision Support)",
  search: "تلاش کریں (Search)",
  close: "بند کریں (Close)",
  reviewed: "ڈاکٹر نے جائزہ لیا (Reviewed)",
  pending: "زیرِ جائزہ (Pending Review)",
  loginAsDoctor: "بطور ڈاکٹر لاگ ان (Login as Doctor)",
  loginAsPatient: "بطور مریض لاگ ان (Login as Patient)",
  planPendingMessage: 'یہ معلومات ابتدائی ہیں اور ڈاکٹر کی منظوری کے بعد حتمی ہوں گی۔ ڈاکٹر کی ہدایات جلد یہاں ظاہر ہوں گی۔',
  requestDataDeletion: "ڈیٹا ڈیلیٹ کرنے کی درخواست",
  dataDeletionConfirmation: "آپ کا ڈیٹا ڈیلیٹ کرنے کی درخواست موصول ہوگئی ہے۔ ہماری ٹیم 30 دن کے اندر آپ سے رابطہ کرے گی۔"
};

export const uiStrings: Record<Language, any> = {
  en: enStrings,
  ur: urStrings,
};
